/* Verilog netlist generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 1.6 */
/* D:\lscc\diamond\3.10_x64\ispfpga\bin\nt64\scuba.exe -w -n sin -lang verilog -synth lse -bus_exp 7 -bb -arch xo2c00 -type cosine -addr_width 8 -width 8 -input_reg -mode 4 -output_reg -area -pipeline 1  */
/* Wed Aug 10 20:14:39 2022 */


`timescale 1 ns / 1 ps
module sin (Clock, ClkEn, Reset, Theta, Sine)/* synthesis NGD_DRC_MASK=1 */;
    input wire Clock;
    input wire ClkEn;
    input wire Reset;
    input wire [7:0] Theta;
    output wire [7:0] Sine;

    wire func_or_inet;
    wire lx_ne0;
    wire lx_ne0_inv;
    wire mx_ctrl_r_inv;
    wire rom_addr0_r_n_6;
    wire rom_addr0_r;
    wire rom_addr0_r_n_7;
    wire rom_addr0_r_1;
    wire rom_addr0_r_n_8;
    wire rom_addr0_r_2;
    wire rom_addr0_r_n_9;
    wire rom_addr0_r_3;
    wire rom_addr0_r_n_10;
    wire rom_addr0_r_4;
    wire rom_addr0_r_n_11;
    wire mx_ctrl_r;
    wire rom_addr0_r_5;
    wire mx_ctrl_r_1;
    wire rom_dout;
    wire rom_dout_1;
    wire rom_dout_2;
    wire rom_dout_3;
    wire rom_dout_4;
    wire rom_dout_5;
    wire rom_dout_6;
    wire sinromoutsel;
    wire rom_dout_7;
    wire out_sel_i;
    wire rom_dout_8;
    wire rom_dout_9;
    wire rom_dout_10;
    wire rom_dout_11;
    wire rom_dout_12;
    wire rom_dout_13;
    wire rom_dout_14;
    wire out_sel;
    wire rom_dout_15;
    wire sinout_pre;
    wire sinout_pre_1;
    wire sinout_pre_2;
    wire sinout_pre_3;
    wire sinout_pre_4;
    wire sinout_pre_5;
    wire sinout_pre_6;
    wire sinout_pre_7;
    wire rom_addr0_r_n;
    wire rom_addr0_r_inv;
    wire rom_addr0_r_n_1;
    wire rom_addr0_r_n_2;
    wire co0;
    wire rom_addr0_r_1_inv;
    wire rom_addr0_r_2_inv;
    wire rom_addr0_r_n_3;
    wire rom_addr0_r_n_4;
    wire co1;
    wire rom_addr0_r_3_inv;
    wire rom_addr0_r_4_inv;
    wire rom_addr0_r_n_5;
    wire co2;
    wire rom_addr0_r_5_inv;
    wire rom_dout_n;
    wire scuba_vhi;
    wire rom_dout_inv;
    wire rom_dout_n_1;
    wire rom_dout_n_2;
    wire co0_1;
    wire rom_dout_1_inv;
    wire rom_dout_2_inv;
    wire rom_dout_n_3;
    wire rom_dout_n_4;
    wire co1_1;
    wire rom_dout_3_inv;
    wire rom_dout_4_inv;
    wire rom_dout_n_5;
    wire rom_dout_n_6;
    wire co2_1;
    wire rom_dout_5_inv;
    wire rom_dout_6_inv;
    wire rom_dout_n_7;
    wire co3;
    wire rom_dout_7_inv;
    wire scuba_vlo;

    INV INV_15 (.A(rom_addr0_r_5), .Z(rom_addr0_r_5_inv));

    INV INV_14 (.A(rom_addr0_r_4), .Z(rom_addr0_r_4_inv));

    INV INV_13 (.A(rom_addr0_r_3), .Z(rom_addr0_r_3_inv));

    INV INV_12 (.A(rom_addr0_r_2), .Z(rom_addr0_r_2_inv));

    INV INV_11 (.A(rom_addr0_r_1), .Z(rom_addr0_r_1_inv));

    INV INV_10 (.A(rom_addr0_r), .Z(rom_addr0_r_inv));

    INV INV_9 (.A(rom_dout_7), .Z(rom_dout_7_inv));

    INV INV_8 (.A(rom_dout_6), .Z(rom_dout_6_inv));

    INV INV_7 (.A(rom_dout_5), .Z(rom_dout_5_inv));

    INV INV_6 (.A(rom_dout_4), .Z(rom_dout_4_inv));

    INV INV_5 (.A(rom_dout_3), .Z(rom_dout_3_inv));

    INV INV_4 (.A(rom_dout_2), .Z(rom_dout_2_inv));

    INV INV_3 (.A(rom_dout_1), .Z(rom_dout_1_inv));

    INV INV_2 (.A(rom_dout), .Z(rom_dout_inv));

    defparam LUT4_1.initval =  16'hfffe ;
    ROM16X1A LUT4_1 (.AD3(rom_addr0_r_n_6), .AD2(rom_addr0_r_n_7), .AD1(rom_addr0_r_n_8), 
        .AD0(rom_addr0_r_n_9), .DO0(func_or_inet));

    defparam LUT4_0.initval =  16'hfffe ;
    ROM16X1A LUT4_0 (.AD3(func_or_inet), .AD2(rom_addr0_r_n_10), .AD1(rom_addr0_r_n_11), 
        .AD0(scuba_vlo), .DO0(lx_ne0));

    INV INV_1 (.A(lx_ne0), .Z(lx_ne0_inv));

    INV INV_0 (.A(mx_ctrl_r), .Z(mx_ctrl_r_inv));

    AND2 AND2_t0 (.A(mx_ctrl_r_inv), .B(lx_ne0_inv), .Z(out_sel_i));

    defparam triglut_1_0_0_0.INIT_DATA = "STATIC" ;
    defparam triglut_1_0_0_0.ASYNC_RESET_RELEASE = "SYNC" ;
    defparam triglut_1_0_0_0.INITVAL_1F = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_1E = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_1D = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_1C = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_1B = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_1A = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_19 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_18 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_17 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_16 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_15 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_14 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_13 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_12 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_11 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_10 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0F = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0E = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0D = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0C = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0B = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_0A = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_09 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_08 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_07 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_06 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_05 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_04 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_03 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_02 = "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000" ;
    defparam triglut_1_0_0_0.INITVAL_01 = "0x006060120D0201302C190381F044250502B05C31068370743C07E42088470944C09E510A8560B05B" ;
    defparam triglut_1_0_0_0.INITVAL_00 = "0x0BA5F0C2630CA670D26A0D86E0DE710E4740EA760EE790F47A0F67C0FA7E0FC7F0FE7F0FE7F0FE7F" ;
    defparam triglut_1_0_0_0.CSDECODE_B = "0b111" ;
    defparam triglut_1_0_0_0.CSDECODE_A = "0b000" ;
    defparam triglut_1_0_0_0.WRITEMODE_B = "NORMAL" ;
    defparam triglut_1_0_0_0.WRITEMODE_A = "NORMAL" ;
    defparam triglut_1_0_0_0.GSR = "ENABLED" ;
    defparam triglut_1_0_0_0.RESETMODE = "ASYNC" ;
    defparam triglut_1_0_0_0.REGMODE_B = "NOREG" ;
    defparam triglut_1_0_0_0.REGMODE_A = "NOREG" ;
    defparam triglut_1_0_0_0.DATA_WIDTH_B = 9 ;
    defparam triglut_1_0_0_0.DATA_WIDTH_A = 9 ;
    DP8KC triglut_1_0_0_0 (.DIA8(scuba_vlo), .DIA7(scuba_vlo), .DIA6(scuba_vlo), 
        .DIA5(scuba_vlo), .DIA4(scuba_vlo), .DIA3(scuba_vlo), .DIA2(scuba_vlo), 
        .DIA1(scuba_vlo), .DIA0(scuba_vlo), .ADA12(scuba_vlo), .ADA11(scuba_vlo), 
        .ADA10(scuba_vlo), .ADA9(scuba_vlo), .ADA8(rom_addr0_r_n_11), .ADA7(rom_addr0_r_n_10), 
        .ADA6(rom_addr0_r_n_9), .ADA5(rom_addr0_r_n_8), .ADA4(rom_addr0_r_n_7), 
        .ADA3(rom_addr0_r_n_6), .ADA2(scuba_vlo), .ADA1(scuba_vlo), .ADA0(scuba_vhi), 
        .CEA(ClkEn), .OCEA(ClkEn), .CLKA(Clock), .WEA(scuba_vlo), .CSA2(scuba_vlo), 
        .CSA1(scuba_vlo), .CSA0(scuba_vlo), .RSTA(Reset), .DIB8(scuba_vlo), 
        .DIB7(scuba_vlo), .DIB6(scuba_vlo), .DIB5(scuba_vlo), .DIB4(scuba_vlo), 
        .DIB3(scuba_vlo), .DIB2(scuba_vlo), .DIB1(scuba_vlo), .DIB0(scuba_vlo), 
        .ADB12(scuba_vlo), .ADB11(scuba_vlo), .ADB10(scuba_vlo), .ADB9(scuba_vlo), 
        .ADB8(scuba_vlo), .ADB7(scuba_vlo), .ADB6(scuba_vlo), .ADB5(scuba_vlo), 
        .ADB4(scuba_vlo), .ADB3(scuba_vlo), .ADB2(scuba_vlo), .ADB1(scuba_vlo), 
        .ADB0(scuba_vlo), .CEB(scuba_vhi), .OCEB(scuba_vhi), .CLKB(scuba_vlo), 
        .WEB(scuba_vlo), .CSB2(scuba_vlo), .CSB1(scuba_vlo), .CSB0(scuba_vlo), 
        .RSTB(scuba_vlo), .DOA8(), .DOA7(rom_dout_7), .DOA6(rom_dout_6), 
        .DOA5(rom_dout_5), .DOA4(rom_dout_4), .DOA3(rom_dout_3), .DOA2(rom_dout_2), 
        .DOA1(rom_dout_1), .DOA0(rom_dout), .DOB8(), .DOB7(), .DOB6(), .DOB5(), 
        .DOB4(), .DOB3(), .DOB2(), .DOB1(), .DOB0())
             /* synthesis MEM_LPC_FILE="sin.lpc" */
             /* synthesis MEM_INIT_FILE="" */;

    FD1P3DX FF_17 (.D(Theta[0]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_16 (.D(Theta[1]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_1))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_15 (.D(Theta[2]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_2))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_14 (.D(Theta[3]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_3))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_13 (.D(Theta[4]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_4))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_12 (.D(Theta[5]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(rom_addr0_r_5))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_11 (.D(Theta[6]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_10 (.D(Theta[7]), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(mx_ctrl_r_1))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_21 (.D0(rom_addr0_r_n), .D1(rom_addr0_r), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_6));

    MUX21 muxb_20 (.D0(rom_addr0_r_n_1), .D1(rom_addr0_r_1), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_7));

    MUX21 muxb_19 (.D0(rom_addr0_r_n_2), .D1(rom_addr0_r_2), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_8));

    MUX21 muxb_18 (.D0(rom_addr0_r_n_3), .D1(rom_addr0_r_3), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_9));

    MUX21 muxb_17 (.D0(rom_addr0_r_n_4), .D1(rom_addr0_r_4), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_10));

    MUX21 muxb_16 (.D0(rom_addr0_r_n_5), .D1(rom_addr0_r_5), .SD(mx_ctrl_r), 
        .Z(rom_addr0_r_n_11));

    FD1P3DX FF_9 (.D(mx_ctrl_r_1), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(sinromoutsel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_15 (.D0(rom_dout), .D1(rom_dout_n), .SD(sinromoutsel), .Z(rom_dout_8));

    MUX21 muxb_14 (.D0(rom_dout_1), .D1(rom_dout_n_1), .SD(sinromoutsel), 
        .Z(rom_dout_9));

    MUX21 muxb_13 (.D0(rom_dout_2), .D1(rom_dout_n_2), .SD(sinromoutsel), 
        .Z(rom_dout_10));

    MUX21 muxb_12 (.D0(rom_dout_3), .D1(rom_dout_n_3), .SD(sinromoutsel), 
        .Z(rom_dout_11));

    MUX21 muxb_11 (.D0(rom_dout_4), .D1(rom_dout_n_4), .SD(sinromoutsel), 
        .Z(rom_dout_12));

    MUX21 muxb_10 (.D0(rom_dout_5), .D1(rom_dout_n_5), .SD(sinromoutsel), 
        .Z(rom_dout_13));

    MUX21 muxb_9 (.D0(rom_dout_6), .D1(rom_dout_n_6), .SD(sinromoutsel), 
        .Z(rom_dout_14));

    MUX21 muxb_8 (.D0(rom_dout_7), .D1(rom_dout_n_7), .SD(sinromoutsel), 
        .Z(rom_dout_15));

    FD1P3DX FF_8 (.D(out_sel_i), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(out_sel))
             /* synthesis GSR="ENABLED" */;

    MUX21 muxb_7 (.D0(rom_dout_8), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre));

    MUX21 muxb_6 (.D0(rom_dout_9), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_1));

    MUX21 muxb_5 (.D0(rom_dout_10), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_2));

    MUX21 muxb_4 (.D0(rom_dout_11), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_3));

    MUX21 muxb_3 (.D0(rom_dout_12), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_4));

    MUX21 muxb_2 (.D0(rom_dout_13), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_5));

    MUX21 muxb_1 (.D0(rom_dout_14), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_6));

    MUX21 muxb_0 (.D0(rom_dout_15), .D1(scuba_vlo), .SD(out_sel), .Z(sinout_pre_7));

    FD1P3DX FF_7 (.D(sinout_pre), .SP(ClkEn), .CK(Clock), .CD(Reset), .Q(Sine[0]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_6 (.D(sinout_pre_1), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[1]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_5 (.D(sinout_pre_2), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[2]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_4 (.D(sinout_pre_3), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[3]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_3 (.D(sinout_pre_4), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[4]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_2 (.D(sinout_pre_5), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[5]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_1 (.D(sinout_pre_6), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[6]))
             /* synthesis GSR="ENABLED" */;

    FD1P3DX FF_0 (.D(sinout_pre_7), .SP(ClkEn), .CK(Clock), .CD(Reset), 
        .Q(Sine[7]))
             /* synthesis GSR="ENABLED" */;

    FADD2B neg_rom_addr0_r_n_0 (.A0(scuba_vlo), .A1(rom_addr0_r_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .CI(scuba_vlo), .COUT(co0), .S0(), .S1(rom_addr0_r_n));

    FADD2B neg_rom_addr0_r_n_1 (.A0(rom_addr0_r_1_inv), .A1(rom_addr0_r_2_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co0), .COUT(co1), .S0(rom_addr0_r_n_1), 
        .S1(rom_addr0_r_n_2));

    FADD2B neg_rom_addr0_r_n_2 (.A0(rom_addr0_r_3_inv), .A1(rom_addr0_r_4_inv), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co1), .COUT(co2), .S0(rom_addr0_r_n_3), 
        .S1(rom_addr0_r_n_4));

    FADD2B neg_rom_addr0_r_n_3 (.A0(rom_addr0_r_5_inv), .A1(scuba_vlo), 
        .B0(scuba_vlo), .B1(scuba_vlo), .CI(co2), .COUT(), .S0(rom_addr0_r_n_5), 
        .S1());

    VHI scuba_vhi_inst (.Z(scuba_vhi));

    FADD2B neg_rom_dout_n_0 (.A0(scuba_vlo), .A1(rom_dout_inv), .B0(scuba_vlo), 
        .B1(scuba_vhi), .CI(scuba_vlo), .COUT(co0_1), .S0(), .S1(rom_dout_n));

    FADD2B neg_rom_dout_n_1 (.A0(rom_dout_1_inv), .A1(rom_dout_2_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co0_1), .COUT(co1_1), .S0(rom_dout_n_1), .S1(rom_dout_n_2));

    FADD2B neg_rom_dout_n_2 (.A0(rom_dout_3_inv), .A1(rom_dout_4_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co1_1), .COUT(co2_1), .S0(rom_dout_n_3), .S1(rom_dout_n_4));

    FADD2B neg_rom_dout_n_3 (.A0(rom_dout_5_inv), .A1(rom_dout_6_inv), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co2_1), .COUT(co3), .S0(rom_dout_n_5), .S1(rom_dout_n_6));

    VLO scuba_vlo_inst (.Z(scuba_vlo));

    FADD2B neg_rom_dout_n_4 (.A0(rom_dout_7_inv), .A1(scuba_vlo), .B0(scuba_vlo), 
        .B1(scuba_vlo), .CI(co3), .COUT(), .S0(rom_dout_n_7), .S1());



    // exemplar begin
    // exemplar attribute triglut_1_0_0_0 MEM_LPC_FILE sin.lpc
    // exemplar attribute triglut_1_0_0_0 MEM_INIT_FILE 
    // exemplar attribute FF_17 GSR ENABLED
    // exemplar attribute FF_16 GSR ENABLED
    // exemplar attribute FF_15 GSR ENABLED
    // exemplar attribute FF_14 GSR ENABLED
    // exemplar attribute FF_13 GSR ENABLED
    // exemplar attribute FF_12 GSR ENABLED
    // exemplar attribute FF_11 GSR ENABLED
    // exemplar attribute FF_10 GSR ENABLED
    // exemplar attribute FF_9 GSR ENABLED
    // exemplar attribute FF_8 GSR ENABLED
    // exemplar attribute FF_7 GSR ENABLED
    // exemplar attribute FF_6 GSR ENABLED
    // exemplar attribute FF_5 GSR ENABLED
    // exemplar attribute FF_4 GSR ENABLED
    // exemplar attribute FF_3 GSR ENABLED
    // exemplar attribute FF_2 GSR ENABLED
    // exemplar attribute FF_1 GSR ENABLED
    // exemplar attribute FF_0 GSR ENABLED
    // exemplar end

endmodule
