/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 1.6 */
/* Wed Aug 10 20:14:39 2022 */

/* parameterized module instance */
sin __ (.Clock( ), .ClkEn( ), .Reset( ), .Theta( ), .Sine( ));
