/* Verilog module instantiation template generated by SCUBA Diamond (64-bit) 3.10.3.144 */
/* Module Version: 5.7 */
/* Tue Aug 02 00:54:55 2022 */

/* parameterized module instance */
pll __ (.CLKI( ), .CLKOP( ));
